apps/central/urls.py
# from django.views.generic import TemplateView
from django.urls import path

from .views import TopicsList, TopicView, TestView


app_name = 'central'
urlpatterns = (
    path('', TopicsList.as_view(), name='index'),
    path('topic/<int:pk>/', TopicView.as_view(), name='topic'),
    path('test/<int:pk>/', TestView.as_view(), name='test'),
)

apps/myauth/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    RegisterView
)


app_name = 'myauth'
urlpatterns = (
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration')
)

conf/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ru/', include('apps.central.urls', namespace='central')),
    path('auth/', include('apps.myauth.urls', namespace='myauth')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/central/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):

    title = models.CharField(max_length=128)
    link = models.URLField(null=True, blank=True)
    video = models.CharField(max_length=256, blank=True, null=True)
    gif = models.CharField(max_length=256, blank=True, null=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    show = models.BooleanField(default=True)


class Test(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, blank=True, null=True)


class Question(models.Model):

    text = models.TextField()
    test = models.ForeignKey('Test', on_delete=models.CASCADE)


class Answer(models.Model):

    text = models.CharField(max_length=120)
    right = models.BooleanField(default=False)
    questions = models.ForeignKey('Question', on_delete=models.CASCADE)


class Result(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, blank=True, null=True)
    right_answers = models.PositiveIntegerField(default=0)

apps/myauth/models.py
from django.db import models

# Create your models here.

apps/central/views.py
import random

from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from .models import (
    Topic,
    Test,
    Question,
    Answer,
    Result,
)


class TopicsList(View):

    def get(self, request):

        topics = Topic.objects.filter(show=True)
        return render(request, 'central/index.html', {'topics': topics})


class TopicView(View):

    def get(self, request, pk):
        topic = get_object_or_404(Topic, pk=pk)
        if not topic.show:
            return redirect('/')
        return render(request, 'central/topic.html', {'topic': topic})


class TestView(View):

    def get(self, request, pk):
        topic = get_object_or_404(Topic, pk=pk)
        test = Test.objects.get(topic=topic)
        questions = test.question_set.all()
        context = {'results': [], 'topic_id': pk}
        for q in questions:
            ans = list(q.answer_set.all())
            random.shuffle(ans)
            context['results'].append({'q': q, 'ans': ans})

        return render(request, 'central/test.html', context)

    def post(self, request, pk):
        data = request.POST
        print(data)
        topic = get_object_or_404(Topic, pk=pk)
        test = Test.objects.get(topic=topic)
        q_count = test.question_set.all().count()

        count = 0
        for d in data:
            try:
                index = int(d)
                ans = Answer.objects.get(pk=index)
                if ans.right:
                    count += 1
            except ValueError:
                pass

        try:
            Result.objects.update_or_create(user=request.user, topic=topic, defaults={'right_answers': count})
        except TypeError:
            pass

        return render(request, 'central/final.html', {'count': count, 'q_count': q_count,
                                                      't_id': topic.id})

apps/myauth/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout, models
from django.views import View


class LoginView(View):

    def get(self, request):
        return render(request, 'auth/login.html', {})

    def post(self, request):
        data = request.POST
        user = authenticate(username=data['username'], password=data['password'])
        if user:
            login(request, user)
            return redirect(reverse('central:index'))
        else:
            return render(request, 'auth/login.html', {})


class LogoutView(View):
    """Logout view"""

    def get(self, request):
        """GET"""
        logout(request)
        return redirect(reverse('central:index'))


class RegisterView(View):
    """Register view"""

    def get(self, request):
        """GET"""
        return render(request, 'auth/register.html')

    def post(self, request):
        """POST"""
        data = request.POST
        error = self.validation(data)
        if not error:
            user, created = models.User.objects.get_or_create(username=data.get('username'))
            if created:
                user.set_password(data.get('password'))
                user.save()
                login(request, user)
                return redirect(reverse('central:index'))
            else:
                return render(request, 'auth/register.html', {'error': 'Пользователь уже существует'})
        else:
            return render(request, 'auth/register.html', {'error': error})

    @staticmethod
    def validation(data):
        """Fields validation"""
        if not (data.get('username') or data.get('password') or data.get('password1')):
            return "Заполните все поля"
        if data.get('password') != data.get('password1'):
            return 'Пароли не совпадают'

apps/central/templates/central/final.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3>Спасибо за прохождение теста!</h3>
    <p class="зн-4">Ваш результат: {{ count }} правильных ответов из {{ q_count }}</p>

    <p>
        <a href="{% url 'central:topic' t_id %}">Вернуться к изучению материала</a>
    </p>
</div>

{% endblock %}

apps/central/templates/central/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Темы для изучения</h1>
        {% for topic in topics %}
            <p>
                <a href="topic/{{ topic.id }}/">{{ topic.title }}</a>
            </p>
        {% endfor %}
    </div>
{% endblock %}

apps/central/templates/central/test.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% if message %}
            <h4 class="py-4">{{ message }}</h4>
        {% endif %}
        {% if results %}
            <p class="pt-5"><a href="/ru/topic/{{ topic_id }}/">Вернуться к теории</a></p>
            <form method="POST">
            {% csrf_token %}
            {% for obj in results %}
                <h5 class="py-3">{{ obj.q.text | safe }}</h5>
                {% for a in obj.ans %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="{{ obj.q.id }}" id="{{ a.id }}" value="{{ a.text }}">
                      <label class="form-check-label" for="{{ a.id }}">
                        {{ a.text }}
                      </label>
                    </div>
                {% endfor %}
            {% endfor %}
            <input type="submit" value="Send" class="btn btn-primary">
            </form>
        {% endif %}
    </div>
{% endblock %}

apps/central/templates/central/topic.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="py-4">{{ topic.title }}</h1>
        {% if topic.link %}
            <img src="{{ topic.link }}" class="py-5" align="top" height="350px" alt="img">
        {% endif %}
        {% if topic.video %}
            {{ topic.video | safe }}
        {% endif %}
        {% if topic.gif %}
            <img src="{{ topic.gif }}" alt="">
        {% endif %}
        <p class="pt-3">{{ topic.text }}</p>
        <span class="py-3">{{ topic.date }}</span>
        <p class="py-5">
            <a href="{% url 'central:test' topic.id %}" class="btn btn-primary bk-bs-btn-sm">Перейти к тесту</a>
        </p>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SimpleSite</title>
  </head>
  <body>
    {% include './includes/_navbar.html' %}
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/includes/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container"> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar18">
  <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbar18"> <a class="navbar-brand d-none d-md-block" href="{% url 'central:index' %}">
      <i class="fa d-inline fa-lg fa-circle"></i>
      <b>SimpleSite`</b>
      </a>
      <ul class="navbar-nav mx-auto">
          <li class="nav-item"> <a class="nav-link text-white" href="{% url 'central:index' %}">Home</a></li>
        <li class="nav-item"> <a class="nav-link text-white" href="/admin">Dashboard</a></li>
      </ul>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
            <li class="nav-item"><p class="nav-link">{{ request.user.username }}</p></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'myauth:logout' %}">Log out</a> </li>
        {% else %}
          <li class="nav-item"> <a class="nav-link" href="{% url 'myauth:login' %}">Log in</a> </li>
          <li class="nav-item"> <a class="nav-link text-white" href="{% url 'myauth:registration' %}">Register</a> </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>